name: fyfypay
description: A Fyfy Mobile Wallet

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.1.0
  fluttertoast: ^8.2.1
  passcode_screen: ^2.0.1
#  solana:
#    git:
#      url: git://github.com/cryptoplease/cryptoplease-dart.git
#      path: packages/solana
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  redux_persist: ^0.9.0
  redux_persist_flutter: ^0.9.0
  tuple: ^2.0.1
  google_fonts: ^4.0.3
  bip39: ^1.0.6
  worker_manager: any
  url_launcher: ^6.1.10
  qr_code_scanner: ^1.0.1
  numeric_keyboard: ^1.1.0
  english_words: ^4.0.0
  lite_rolling_switch: ^1.0.1
  qr_flutter: ^4.0.0
  slidable_button: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/app_logo.png"

  flutter_lints: ^2.0.1

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/fonts/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
